### ISSUE TITLE
many dialogs don't close when application closes

### ISSUE THREAD

**Issue by gr5** [githubdoe/DFTFringe#82]
**To Reproduce**
**zernike smoothing**

**For the following, first process an igram to get a wavefront.  Then:**

1. Do "tools" "smooth current wave front".  Before doing anything with this dialog close the app.  The dialog stays running and the DFTF icon is still visible as an actively running application.

1. tools  wavefront inspector
2. view show statistics of loaded wavefronts

**needs igram loaded but not a wavefront**
1.tools outline helper

**others - just launch dialog and close window:**
1. tools user color map
1. tools test stand astig removal
3. tools camera calibration
4. tools astig stats
5. config mirror
6. config preferences

tools tilt versus astig analysis - first you need to create a zernike csv file.  With one or more wavefronts loaded do "file" "save zernike values in csv".  Then run the astig analysis off the csv file.

**Expected behavior**
all dialogs should close when closing DFTF main window.

**Desktop (please complete the following information):**
win11, master branch as of 8/23/23 - probably will become v7.0.0

**Comment by atsju** [comment]
This one is for me I think. I will love to write all these clean destructors :)

**Comment by atsju** [comment]
### wft needed

- [ ] 1. Do "tools" "smooth current wave front". Before doing anything with this dialog close the app. The dialog stays running and the DFTF icon is still visible as an actively running application.
- [ ] 2. tools wavefront inspector
- [ ] 3. view show statistics of loaded wavefronts
- [ ] 4. Click full screen above the 3d window, alt-tab to app, close app
- [ ] 5. right click upper right wavefront coutour chart. Choose "full screen". alt-tab to app and close app.

### needs igram loaded but not a wavefront
- [x] 1. tools outline helper

### others - just launch dialog and close window:

- [x] 1. tools user color map (#84)
- [x] 2. tools test stand astig removal (#93)
- [x] 3. tools camera calibration (#95)
- [x] 4. tools astig stats => not reproduced on Linux and Windows with v7.0.0
- [x] 5. config mirror (#96)
- [x] 6. config preferences (#102)

**Comment by atsju** [comment]
at e25f5405effce2c3aa6a444e45bf918151102c71 with every preidentified problems already fixed.
AI found 6 remaining user-facing cases in this branch that can still behave like orphan windows after closing the main app.

To investigate manually each of them.

# Astig stats distribution popup
Code evidence: astigstatsdlg.cpp:729, astigstatsdlg.cpp:934, opened from mainwindow.cpp:1549
Why risky: distribution window is created as parentless QWidget and shown modeless.
Repro sequence:
Open Tools -> astig Stats.

In the astig stats dialog, click Distribution.

Close the main app window.

The Distribution window can remain open independently.

# Defocus adjustment dialog

Code evidence: surfaceanalysistools.cpp:346, surfaceanalysistools.cpp:349
Why risky: dialog is created with no parent and shown modeless.
Repro sequence:
Go to Results tab.

In Surface Analysis Tools, click Defocus Adjustment.

Close the main app window.

Defocus dialog can stay open.

# Create movie flow: astig preview window

Code evidence: mainwindow.cpp:1672, mainwindow.cpp:1715, mainwindow.cpp:1719
Why risky: astig preview window is a parentless QWidget.
Repro sequence:
Open Tools -> Create Movie of wavefronts.

Choose the astig movie path when prompted.

Let the astig preview window appear.

Close main app.

Astig preview window can remain.

# Create movie flow: ffmpeg output dialog

Code evidence: mainwindow.cpp:1805, mainwindow.cpp:1820
Why risky: ffmpeg output dialog is created parentless and shown modeless.
Repro sequence:
Open Tools -> Create Movie of wavefronts.

Continue to the ffmpeg step and open output dialog.

Close main app.

ffmpeg output dialog can remain.

# 3D show selected results window

Code evidence: oglview.cpp:168, oglview.cpp:206, oglview.cpp:232
Why risky: window is created as parentless QWidget and shown modeless.
Repro sequence:
Go to Results tab, 3D view.

Click Show selected.

Close main app.

The generated 3D summary window can remain.

# Show all contours result window

Code evidence: contourview.cpp:100, contourview.cpp:102, surfacemanager.cpp:2872, surfacemanager.cpp:2932, surfacemanager.cpp:2957
Why risky: output window is parentless QWidget and shown modeless.
Repro sequence:
Go to contour view and press the Show all contours button.
Generate the contours montage window.
Close main app.
Contours montage window can remain.

# Optional additional high-risk case:

Stand astig analysis tab window is also parentless: surfacemanager.cpp:2773, surfacemanager.cpp:2784, triggered from mainwindow.cpp:973.
If you run that workflow to completion, the report tabs window may also survive app close.
